// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSlwG4TyL1oBAQ-B2xigK_Q2h_ucajFHo',
    appId: '1:365820859466:web:aed62f86928ad31c8582b3',
    messagingSenderId: '365820859466',
    projectId: 'banana-57559',
    authDomain: 'banana-57559.firebaseapp.com',
    storageBucket: 'banana-57559.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjaOn20FP4dN2Ogrp8oiH0tAeyPIyDo6I',
    appId: '1:365820859466:android:89958f537950d5c18582b3',
    messagingSenderId: '365820859466',
    projectId: 'banana-57559',
    storageBucket: 'banana-57559.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDchjmtRLFKabbZOJ0JAPLyvF8SMR3tDOk',
    appId: '1:365820859466:ios:0905244f7946b99c8582b3',
    messagingSenderId: '365820859466',
    projectId: 'banana-57559',
    storageBucket: 'banana-57559.firebasestorage.app',
    iosClientId: '365820859466-vf9cvbfnjkj3hr0u2g8m59269f0svnre.apps.googleusercontent.com',
    iosBundleId: 'com.giang.handstand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDchjmtRLFKabbZOJ0JAPLyvF8SMR3tDOk',
    appId: '1:365820859466:ios:7720e3b6e67f9f1b8582b3',
    messagingSenderId: '365820859466',
    projectId: 'banana-57559',
    storageBucket: 'banana-57559.firebasestorage.app',
    iosClientId: '365820859466-qaaku3igl9ojaj1sfa3faq2e29btkgkk.apps.googleusercontent.com',
    iosBundleId: 'com.example.handstandApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYD7n7laCKq_CVBQrdup1j_sImtcFB7m4',
    appId: '1:365820859466:web:f658d4c67234fc838582b3',
    messagingSenderId: '365820859466',
    projectId: 'banana-57559',
    authDomain: 'banana-57559.firebaseapp.com',
    storageBucket: 'banana-57559.firebasestorage.app',
  );
}
